[package]
name = "nns"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = "0.15"
ndarray-linalg = { version = "0.16", features = ["openblas"] }
ndarray-rand = "0.14"
rand = "0.8"
rand_distr = "0.4"
maplit = "1.0"
